# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutual_fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=50)),
                ('units', models.DecimalField(decimal_places=1, max_digits=10)),
                ('purchase_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('net_asset_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_fund', to='portfolio.Customer')),
            ],
        ),
    ]
