# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_mutual_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutual_fund',
            name='actual_value',
        ),
    ]
