# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_mutual_fund_actual_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutual_fund',
            name='recent_value',
            field=models.DecimalField(decimal_places=2, default=60000, max_digits=10),
            preserve_default=False,
        ),
    ]
